### ISSUE TITLE
Possible update for the newest Intellij?

### ISSUE THREAD

**Issue by Static-Flow** [garyttierney/intellij-ghidra#30]
This plugin would be useful but it only supports 2022 versions of intellij. Any chase this can be upgraded? Willing to help any way I can.

**Comment by garyttierney** [comment]
I _think_ this should be straight forward. If there are no API breaking changes in IntelliJ then it'll be as simple as updating the version constraints here: <https://github.com/garyttierney/intellij-ghidra/blob/main/gradle.properties#L11>.

You're welcome to take a look and send a PR, but I can bump this over the weekend and see if it's enough to get a new version on the plugin portal.

**Comment by Static-Flow** [comment]
Looks like that's all it took. I can make a PR here shortly.

**Comment by garyttierney** [comment]
It also might be possible to remove the `untilBuild` constraint completely, making it compatible with all future builds without needing to bump `gradle.properties` every release. The JetBrains plugin verifier tends to warn about usage of APIs that no longer exist anyway.

**Comment by agatti** [comment]
Any chance to get something going for 2023.2? :)

**Comment by garyttierney** [comment]
Resolved by https://github.com/garyttierney/intellij-ghidra/pull/32
