### ISSUE TITLE
XDG support

### ISSUE THREAD

**Issue by fridtjof** [garyttierney/intellij-ghidra#34]
Ghidra 11.1 will start supporting the XDG Base Directory Specification: https://github.com/NationalSecurityAgency/ghidra/issues/908

`GhidraFacetConfiguration` is currently only looking at `$HOME/.ghidra`, this should be expanded to also look at everything else according to [ApplicationUtilities.getDefaultUserSettingsDir](https://github.com/NationalSecurityAgency/ghidra/blob/5e9cfe2419329094b6a83e9532f7a81f3e39126d/Ghidra/Framework/Utility/src/main/java/utility/application/ApplicationUtilities.java#L246)

(getLegacyUserSettingsDir is the old implementation used as a fallback if it does not find anything else)

**Comment by garyttierney** [comment]
Thanks! I'll be looking at this as a part of updating the plugin to use more recent IDE features.

**Comment by garyttierney** [comment]
Fixed in a4378e5b0fcce727c9bc8e91cd64a5c803f36f98. The plugin will now load the Ghidra `Utility.jar` to figure out the actual application layout.
